eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://user:06206daf-2a7a-4077-8c6d-59a35c16b68d@localhost:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-84928916.okta.com/oauth2/default
    audience: api://default
